# Custom Language File for Launcher Customizer

[ejs.app]
title = "REBOOT Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/wAbj9F2crt"
#---------------------------------------------------------------
updateAvailableTooltip = "ระบบมีการอัพเดตใหม่"
usernamePlaceholder = "ชื่อผู้ใช้"
usernameEditButton = "Edit"
settingsTooltip = "ตั้งค่า"
serverStatus = "Server"
serverStatusPlaceholder = "Offline"
mojangStatus = "สถานะ MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "ข่าวสาร"
launchButton = "เล่น"
launchButtonPlaceholder = "&#8226; ไม่ได้เลือกเซิร์ฟเวอร์"
launchDetails = "รอสักครู่.."
newsNavigationStatus = "{currentPage} of {totalPages}"
newsErrorLoadSpan = "กําลังเช็คข่าวสาร.."
newsErrorFailedSpan = "ไม่สามารถโหลดข่าวสารได้"
newsErrorRetryButton = "ลองอีกครั้ง"
newsErrorNoneSpan = "ไม่มีข่าวสาร"

[ejs.overlay]
serverSelectHeader = "เซิร์ฟเวอร์ที่มีอยู่"
serverSelectConfirm = "เลือก"
serverSelectCancel = "ยกเลิก"
accountSelectHeader = "เลือกแอคเค้าท์"
accountSelectConfirm = "เลือก"
accountSelectCancel = "ยกเลิก"

[js.landing.launch]
pleaseWait = "รอสักครู่.."
failureTitle = "Error During Launch"
failureText = "See console (CTRL + Shift + i) for more details."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "No Account Selected"

[js.landing.selectedServer]
noSelection = "ไม่มีเซิฟเวอร์ให้เลือก"
loading = "กําลังโหลด.."

[js.landing.serverStatus]
server = "Server"
offline = "Offline"
players = "Players"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "ยินดีต้อนรับเข้าสู่ REBOOT-PROJECT"
welcomeDescription = ""
welcomeDescCTA = "You are just a few clicks away from Reboot-project."
